--liquibase formatted sql

-- changeset byorck:1
CREATE TABLE users
(
    id        BIGSERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  TEXT NOT NULL,
    password  TEXT NOT NULL,
    firstName TEXT NOT NULL,
    lastName  TEXT NOT NULL,
    phone     TEXT NOT NULL,
    role      TEXT DEFAULT 'USER',
    CONSTRAINT uk_users_id UNIQUE (id)
);
COMMENT ON TABLE users IS 'Таблица с данными пользователей';
COMMENT ON COLUMN users.username IS 'Логин';
COMMENT ON COLUMN users.password IS 'Пароль';
COMMENT ON COLUMN users.firstName IS 'Имя';
COMMENT ON COLUMN users.lastName IS 'Фамилия';
COMMENT ON COLUMN users.phone IS 'Телефон';
COMMENT ON COLUMN users.role IS 'Права пользователя(админ или пользователь)';
