--liquibase formatted sql

-- changeset byorck:1
CREATE TABLE users
(
    id         BIGSERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   TEXT NOT NULL,
    password   TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name  TEXT NOT NULL,
    phone      TEXT NOT NULL,
    role       TEXT DEFAULT 'USER',
    CONSTRAINT uk_users_id UNIQUE (id)
);
COMMENT ON TABLE users IS 'Таблица с данными пользователей';
COMMENT ON COLUMN users.username IS 'Логин(email)';
COMMENT ON COLUMN users.password IS 'Пароль';
COMMENT ON COLUMN users.first_name IS 'Имя';
COMMENT ON COLUMN users.last_name IS 'Фамилия';
COMMENT ON COLUMN users.phone IS 'Телефон';
COMMENT ON COLUMN users.role IS 'Права пользователя(админ или пользователь)';

-- changeset byorck:2
CREATE TABLE avatars
(
    id         BIGSERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    file_path  TEXT,
    file_size  BIGINT,
    media_type TEXT,
    data       BYTEA,
    CONSTRAINT uk_avatar_id UNIQUE (id)
);
COMMENT ON TABLE avatars IS 'Таблица с данными пользователей';
COMMENT ON COLUMN avatars.user_id IS 'ID пользователя';
COMMENT ON COLUMN avatars.file_path IS 'Путь к файлу';
COMMENT ON COLUMN avatars.file_size IS 'Размер файла';
COMMENT ON COLUMN avatars.media_type IS 'Тип файла';
COMMENT ON COLUMN avatars.data IS 'Файл изображения';
COMMENT ON COLUMN avatars.user_id IS 'ID владельца аватара, внешний ключ к таблице users';

-- changeset byorck:3
CREATE TABLE ads
(
    id          BIGSERIAL PRIMARY KEY,
    title       TEXT NOT NULL,
    price       INTEGER,
    description TEXT,
    file_path   TEXT,
    file_size   BIGINT,
    media_type  TEXT,
    data        BYTEA,
    user_id     BIGINT REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_ads_id UNIQUE (id)
);

COMMENT ON TABLE ads IS 'Объявления пользователей';
COMMENT ON COLUMN ads.title IS 'Название объявления';
COMMENT ON COLUMN ads.price IS 'Цена';
COMMENT ON COLUMN ads.description IS 'Описание объявления';
COMMENT ON COLUMN ads.file_path IS 'Путь к файлу медиа';
COMMENT ON COLUMN ads.file_size IS 'Размер файла';
COMMENT ON COLUMN ads.media_type IS 'Тип медиа-файла';
COMMENT ON COLUMN ads.data IS 'Файл изображения';
COMMENT ON COLUMN ads.user_id IS 'ID владельца объявления, внешний ключ к таблице users';

-- changeset byorck:4
CREATE TABLE comments
(
    id         BIGSERIAL PRIMARY KEY,
    text       TEXT   NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    ad_id      BIGINT NOT NULL REFERENCES ads (id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_ad_id ON comments (ad_id);
CREATE INDEX idx_comments_user_id ON comments (user_id);
CREATE INDEX idx_comments_created_at ON comments (created_at DESC);